name: "build with ufbt"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  schedule: 
    # do a build every Sunday to keep up with SDK changes
    - cron: "0 0 * * 0"
jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Official Dev channel
            sdk-channel: dev
          - name: Official Release channel
            sdk-channel: release
          - name: Unleashed Dev
            sdk-index-url: https://up.unleashedflip.com/directory.json
            sdk-channel: dev
          - name: Unleashed Release
            sdk-index-url: https://up.unleashedflip.com/directory.json
            sdk-channel: release
    name: 'fap ufbt build for ${{ matrix.name }}'
    env:
      DEV_SDK: ${{ matrix.sdk-channel == 'dev' }}
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set UFBT_ARGS
        run: |
          echo "UFBT_ARGS=$(if [[ '${{ env.DEV_SDK }}' == 'true' ]]; then echo '--extra-define=DEV_SDK'; else echo '-s'; fi)" >> $GITHUB_ENV
      - name: Build with ufbt (actual)
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
        id: build-app
        with:
          sdk-channel: ${{ matrix.sdk-channel }}
          sdk-index-url: ${{ matrix.sdk-index-url }}
          ufbt-args: ${{ env.UFBT_ARGS }}
      - name: Upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}-build
          path: ${{ steps.build-app.outputs.fap-artifacts }}
